# This is a basic workflow to help you get started with Actions

name: CI-TESTING

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  GIT_TAG: $(git describe --tags $(git rev-list --tags --max-count=1))

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get Git Tag
      run: echo "GIT_TAG=`$GIT_TAG`"
      env:
        GIT_TAG: ${{ env.GIT_TAG }}

