name: TESTING

on:
  push:
    branches:
      - master

env:
  GIT_TAG: $(git describe --tags $(git rev-list --tags --max-count=1))

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get Git Tag
      run: echo "GIT_TAG=$GIT_TAG"
      env:
        GIT_TAG: ${{ env.GIT_TAG }}

